#!/usr/bin/env python3
"""Synthesizes the game's sound cues from scratch (sine/square waves + filtered noise).

Every sound here is original and generated by this script — no samples, no
broadcast audio, no chants, no TV-show stings. Re-run to regenerate:

    python3 tools/scripts/gen-sounds.py
"""
from pathlib import Path

import numpy as np
from scipy.io import wavfile
from scipy.signal import butter, lfilter

SR = 22050
OUT = Path(__file__).resolve().parents[2] / "apps/mobile/assets/sounds"
rng = np.random.default_rng(7)


def t(sec):
    return np.arange(int(SR * sec)) / SR


def env(n, attack=0.005, release=0.08):
    e = np.ones(n)
    a, r = min(int(SR * attack), n // 2), min(int(SR * release), n // 2)
    if a:
        e[:a] = np.linspace(0, 1, a)
    if r:
        e[-r:] *= np.linspace(1, 0, r)
    return e


def tone(freq, sec, kind="sine", vol=0.5, attack=0.005, release=0.08):
    x = t(sec)
    ph = 2 * np.pi * freq * x
    if kind == "square":  # softened square (first 4 odd harmonics)
        w = sum(np.sin(ph * k) / k for k in (1, 3, 5, 7))
    elif kind == "tri":
        w = 2 / np.pi * np.arcsin(np.sin(ph))
    else:
        w = np.sin(ph)
    return vol * w * env(len(x), attack, release)


def noise(sec, lo, hi, vol):
    b, a = butter(2, [lo / (SR / 2), hi / (SR / 2)], btype="band")
    return vol * lfilter(b, a, rng.standard_normal(int(SR * sec)))


def crowd(sec, rise, vol=0.35, lo=250, hi=1800):
    """A swelling murmur: band-limited noise with a slow roar envelope."""
    n = noise(sec, lo, hi, 1.0)
    n /= np.max(np.abs(n)) + 1e-9
    x = t(sec)
    shape = np.clip(x / rise, 0, 1) ** 1.5 * np.clip((sec - x) / (sec * 0.45), 0, 1)
    wobble = 1 + 0.15 * np.sin(2 * np.pi * 3.1 * x) + 0.1 * np.sin(2 * np.pi * 5.3 * x)
    return vol * n * shape * wobble


def seq(*parts, gap=0.0):
    g = np.zeros(int(SR * gap))
    out = []
    for p in parts:
        out += [p, g]
    return np.concatenate(out)


def mix(*tracks):
    n = max(len(x) for x in tracks)
    out = np.zeros(n)
    for x in tracks:
        out[: len(x)] += x
    return out


def whistle(sec):
    x = t(sec)
    trill = 0.55 + 0.45 * np.sign(np.sin(2 * np.pi * 34 * x))  # pea rattle
    w = np.sin(2 * np.pi * (2900 + 40 * np.sin(2 * np.pi * 6 * x)) * x)
    return 0.4 * w * trill * env(len(x), 0.01, 0.05) + noise(sec, 2500, 3500, 0.04)


def save(name, x):
    x = x / max(1.0, np.max(np.abs(x)) / 0.9)
    wavfile.write(OUT / f"{name}.wav", SR, (x * 32767).astype(np.int16))


OUT.mkdir(parents=True, exist_ok=True)

C5, E5, G5, C6, E6, G6 = 523.25, 659.25, 783.99, 1046.5, 1318.5, 1568.0

save("tap", tone(1400, 0.03, "sine", 0.4, 0.001, 0.025))
save("tick", tone(1000, 0.04, "square", 0.25, 0.001, 0.03))
save("answer_lock", seq(tone(880, 0.07, "square", 0.3), tone(1320, 0.09, "square", 0.3), gap=0.015))
save("whistle", seq(whistle(0.22), whistle(0.55), gap=0.08))
save(
    "answer_correct",
    mix(
        seq(*(tone(f, 0.09, "square", 0.32) for f in (C5, E5, G5)), tone(C6, 0.35, "square", 0.32, release=0.25)),
        np.concatenate([np.zeros(int(SR * 0.12)), crowd(1.5, 0.35, 0.38)]),
    ),
)
save(
    "answer_wrong",
    mix(
        seq(tone(311, 0.16, "tri", 0.45), tone(233, 0.42, "tri", 0.45, release=0.3), gap=0.02),
        crowd(1.1, 0.15, 0.22, 120, 700),
    ),
)
save("coins", seq(*(tone(f, 0.07, "sine", 0.35, release=0.06) for f in (G5, C6, E6, G6, C6 * 2)), gap=0.01))
save(
    "level_up",
    mix(
        seq(*(tone(f, 0.11, "square", 0.3) for f in (C5, G5, C6, E6)), tone(G6, 0.5, "square", 0.3, release=0.35)),
        np.concatenate([np.zeros(int(SR * 0.3)), crowd(1.4, 0.4, 0.3)]),
    ),
)
save("var", seq(*(tone(f, 0.05, "sine", 0.3) for f in np.linspace(600, 1800, 10)), tone(1800, 0.2, "sine", 0.3)))
save("pack_open", seq(noise(0.25, 800, 6000, 0.35) * env(int(SR * 0.25), 0.01, 0.2), tone(G6, 0.3, "sine", 0.3)))
save("rare_reveal", seq(*(tone(f, 0.08, "tri", 0.35) for f in (C6, E6, G6, C6 * 2)), tone(E6 * 2, 0.4, "tri", 0.3)))
print("sounds written to", OUT)
