"""Builds the base maps for picture questions from Natural Earth (public domain).

Land and lakes only — no borders, no place names — so the map is neutral and
the player has to recognise the place by its position.

    python3 tools/maps/gen-maps.py <natural-earth geojson dir>  →  packages/shared/src/maps.ts
"""
import json, math, sys
from pathlib import Path

NE = Path(sys.argv[1])
OUT = Path(__file__).resolve().parents[2] / "packages/shared/src/maps.ts"

MAPS = {
    # lon0, lat0, lon1, lat1, width (height follows the projection), land file, simplify tolerance (px)
    "israel": dict(bbox=(33.95, 29.35, 36.05, 33.45), width=200, land="ne_10m_land.geojson", lakes=True, tol=0.6),
    "europe": dict(bbox=(-11.5, 35.0, 31.0, 61.5), width=320, land="ne_50m_land.geojson", lakes=False, tol=0.7),
}

def proj_factory(bbox, width):
    lon0, lat0, lon1, lat1 = bbox
    k = math.cos(math.radians((lat0 + lat1) / 2))
    sx = width / ((lon1 - lon0) * k)
    height = (lat1 - lat0) * sx
    def p(lon, lat):
        return ((lon - lon0) * k * sx, (lat1 - lat) * sx)
    return p, round(height)

def dp(points, tol):
    if len(points) < 3:
        return points
    (x1, y1), (x2, y2) = points[0], points[-1]
    dx, dy = x2 - x1, y2 - y1
    norm = math.hypot(dx, dy) or 1e-9
    imax, dmax = 0, 0.0
    for i in range(1, len(points) - 1):
        x0, y0 = points[i]
        d = abs(dy * x0 - dx * y0 + x2 * y1 - y2 * x1) / norm
        if d > dmax:
            imax, dmax = i, d
    if dmax > tol:
        return dp(points[: imax + 1], tol)[:-1] + dp(points[imax:], tol)
    return [points[0], points[-1]]

def clip(points, w, h, m=2.0):
    """Sutherland–Hodgman: clip a closed ring to the rectangle [-m, w+m] x [-m, h+m]."""
    def inside(pt, edge):
        x, y = pt
        return {"l": x >= -m, "r": x <= w + m, "t": y >= -m, "b": y <= h + m}[edge]
    def cross(a, b, edge):
        (x1, y1), (x2, y2) = a, b
        if edge in ("l", "r"):
            X = -m if edge == "l" else w + m
            t = (X - x1) / (x2 - x1)
            return (X, y1 + t * (y2 - y1))
        Y = -m if edge == "t" else h + m
        t = (Y - y1) / (y2 - y1)
        return (x1 + t * (x2 - x1), Y)
    out = points
    for edge in ("l", "r", "t", "b"):
        if not out:
            break
        inp, out = out, []
        prev = inp[-1]
        for cur in inp:
            if inside(cur, edge):
                if not inside(prev, edge):
                    out.append(cross(prev, cur, edge))
                out.append(cur)
            elif inside(prev, edge):
                out.append(cross(prev, cur, edge))
            prev = cur
    return out

def simplify_ring(pts, tol):
    if len(pts) > 1 and pts[0] == pts[-1]:
        pts = pts[:-1]
    if len(pts) < 4:
        return pts
    # split at the point farthest from the first so neither half is degenerate
    x0, y0 = pts[0]
    j = max(range(len(pts)), key=lambda i: (pts[i][0] - x0) ** 2 + (pts[i][1] - y0) ** 2)
    a = dp(pts[: j + 1], tol)
    b = dp(pts[j:] + [pts[0]], tol)
    return a[:-1] + b[:-1]

def rings(geom):
    if geom["type"] == "Polygon":
        yield from geom["coordinates"]
    elif geom["type"] == "MultiPolygon":
        for poly in geom["coordinates"]:
            yield from poly

def path_for(features, bbox, p, tol, w, h):
    lon0, lat0, lon1, lat1 = bbox
    out = []
    for f in features:
        for ring in rings(f["geometry"]):
            xs = [x for x, _ in ring]; ys = [y for _, y in ring]
            if max(xs) < lon0 or min(xs) > lon1 or max(ys) < lat0 or min(ys) > lat1:
                continue
            pts = clip([p(x, y) for x, y in ring], w, h)
            if len(pts) < 3:
                continue
            pts = simplify_ring(pts, tol)
            if len(pts) < 3:
                continue
            out.append("M" + "L".join(f"{x:.1f} {y:.1f}" for x, y in pts) + "Z")
    return "".join(out)

lines = [
    "/**",
    " * Base maps for picture questions. GENERATED by tools/maps/gen-maps.py from",
    " * Natural Earth (public domain). Land and lakes only: no borders, no names.",
    " */",
    "export interface BaseMap { bbox: [number, number, number, number]; width: number; height: number; land: string; lakes: string }",
    "",
    "export const BASE_MAPS: Record<string, BaseMap> = {",
]
for name, m in MAPS.items():
    p, h = proj_factory(m["bbox"], m["width"])
    land = path_for(json.load(open(NE / m["land"]))["features"], m["bbox"], p, m["tol"], m["width"], h)
    lakes = ""
    if m["lakes"]:
        lakes = path_for(json.load(open(NE / "ne_10m_lakes.geojson"))["features"], m["bbox"], p, 0.3, m["width"], h)
    lines.append(f"  {name}: {{ bbox: {list(m['bbox'])}, width: {m['width']}, height: {h}, land: '{land}', lakes: '{lakes}' }},")
    print(name, m["width"], h, len(land), len(lakes))
lines += [
    "};",
    "",
    "/** Projects a lon/lat onto a base map (same equirectangular projection the paths use). */",
    "export function projectOnMap(map: BaseMap, lon: number, lat: number): { x: number; y: number } {",
    "  const [lon0, lat0, lon1, lat1] = map.bbox;",
    "  const k = Math.cos((((lat0 + lat1) / 2) * Math.PI) / 180);",
    "  const sx = map.width / ((lon1 - lon0) * k);",
    "  return { x: (lon - lon0) * k * sx, y: (lat1 - lat) * sx };",
    "}",
    "",
]
OUT.write_text("\n".join(lines))
