-- General-knowledge albums (drawn in packages/shared/src/knowledgeArt.ts).
-- The football albums stay; the new albums come first in the album list.
update public.albums set sort = sort + 100 where sort < 100;
insert into public.albums (slug, title, blurb, sort, kind) values
  ('animals', 'חיות הבר', 'מהפינגווין הקטן ועד הלווייתן הכחול.', 1, 'knowledge'),
  ('wonders', 'פלאי העולם', 'המקומות שכל העולם בא לראות.', 2, 'knowledge'),
  ('space', 'מסע בחלל', 'כוכבים, כוכבי לכת ומה שמעבר להם.', 3, 'knowledge'),
  ('inventions', 'המצאות ששינו את העולם', 'רעיון אחד שהפך את החיים שלנו.', 4, 'knowledge'),
  ('dinos', 'עולם הדינוזאורים', 'ענקים שחיו כאן לפני מיליוני שנים.', 5, 'knowledge'),
  ('food', 'מטעמי העולם', 'מנות שעושות חשק לטייל.', 6, 'knowledge')
on conflict (slug) do update set title = excluded.title, blurb = excluded.blurb, sort = excluded.sort, kind = excluded.kind;

insert into public.collectibles (id, album, number, rarity, name_he, position, era, bio_he, art_seed, kind) values
  ('animals_01', 'animals', 1, 'common', 'פינגווין', 'OBJ', 'modern', 'לא יודע לעוף, אבל שוחה מהר מאוד מתחת למים.', 20001, 'object'),
  ('animals_02', 'animals', 2, 'common', 'צפרדע', 'OBJ', 'modern', 'נושמת גם דרך העור.', 20002, 'object'),
  ('animals_03', 'animals', 3, 'common', 'ינשוף', 'OBJ', 'modern', 'יכול לסובב את הראש הרבה יותר מאיתנו, עד כ-270 מעלות.', 20003, 'object'),
  ('animals_04', 'animals', 4, 'common', 'צב יבשה', 'OBJ', 'modern', 'יש צבי ענק שחיים יותר מ-100 שנה.', 20004, 'object'),
  ('animals_05', 'animals', 5, 'uncommon', 'ג''ירפה', 'OBJ', 'modern', 'החיה הגבוהה ביותר ביבשה.', 20005, 'object'),
  ('animals_06', 'animals', 6, 'uncommon', 'פיל', 'OBJ', 'modern', 'היונק היבשתי הגדול ביותר.', 20006, 'object'),
  ('animals_07', 'animals', 7, 'uncommon', 'דולפין', 'OBJ', 'modern', 'יונק שנושם אוויר, למרות שהוא חי בים.', 20007, 'object'),
  ('animals_08', 'animals', 8, 'rare', 'זיקית', 'OBJ', 'modern', 'יכולה להזיז כל עין לכיוון אחר.', 20008, 'object'),
  ('animals_09', 'animals', 9, 'rare', 'פנדה', 'OBJ', 'modern', 'אוכלת בעיקר במבוק, שעות רבות ביום.', 20009, 'object'),
  ('animals_10', 'animals', 10, 'epic', 'נמר', 'OBJ', 'modern', 'לכל נמר יש דפוס פסים משלו.', 20010, 'object'),
  ('animals_11', 'animals', 11, 'legendary', 'אריה', 'OBJ', 'modern', 'את השאגה שלו אפשר לשמוע ממרחק של כמה קילומטרים.', 20011, 'object'),
  ('animals_12', 'animals', 12, 'iconic', 'לווייתן כחול', 'OBJ', 'modern', 'החיה הגדולה ביותר שחיה אי פעם על כדור הארץ.', 20012, 'object'),
  ('wonders_01', 'wonders', 1, 'common', 'מגדל פיזה', 'OBJ', 'modern', 'נוטה הצידה כבר מאות שנים, ועדיין עומד.', 20101, 'object'),
  ('wonders_02', 'wonders', 2, 'common', 'ביג בן', 'OBJ', 'modern', 'השם שייך בעצם לפעמון הגדול שבתוך המגדל בלונדון.', 20102, 'object'),
  ('wonders_03', 'wonders', 3, 'common', 'פסל החירות', 'OBJ', 'modern', 'מתנה מצרפת לארצות הברית.', 20103, 'object'),
  ('wonders_04', 'wonders', 4, 'common', 'בית האופרה של סידני', 'OBJ', 'modern', 'הגגות שלו נראים כמו מפרשים.', 20104, 'object'),
  ('wonders_05', 'wonders', 5, 'uncommon', 'מגדל אייפל', 'OBJ', 'modern', 'נבנה לתערוכה העולמית בפריז ב-1889.', 20105, 'object'),
  ('wonders_06', 'wonders', 6, 'uncommon', 'הקולוסיאום', 'OBJ', 'modern', 'זירה עתיקה ברומא שאירחה עשרות אלפי צופים.', 20106, 'object'),
  ('wonders_07', 'wonders', 7, 'uncommon', 'טאג'' מהאל', 'OBJ', 'modern', 'מבנה שיש לבן בהודו שנבנה לזכר אישה אהובה.', 20107, 'object'),
  ('wonders_08', 'wonders', 8, 'rare', 'מאצ''ו פיצ''ו', 'OBJ', 'modern', 'עיר אינקה עתיקה בהרי האנדים בפרו.', 20108, 'object'),
  ('wonders_09', 'wonders', 9, 'rare', 'פטרה', 'OBJ', 'modern', 'עיר שנחצבה בסלע אדמדם בירדן.', 20109, 'object'),
  ('wonders_10', 'wonders', 10, 'epic', 'פסל ישו הגואל', 'OBJ', 'modern', 'ניצב על הר מעל ריו דה ז''ניירו.', 20110, 'object'),
  ('wonders_11', 'wonders', 11, 'legendary', 'החומה הסינית', 'OBJ', 'modern', 'נמתחת לאורך אלפי קילומטרים בצפון סין.', 20111, 'object'),
  ('wonders_12', 'wonders', 12, 'iconic', 'הפירמידה הגדולה', 'OBJ', 'modern', 'היחידה משבעת פלאי תבל העתיקים שעדיין עומדת.', 20112, 'object'),
  ('space_01', 'space', 1, 'common', 'הירח', 'OBJ', 'modern', 'תמיד מראה לנו את אותו הצד.', 20201, 'object'),
  ('space_02', 'space', 2, 'common', 'כוכב שביט', 'OBJ', 'modern', 'כשהוא מתקרב לשמש צומח לו זנב ארוך.', 20202, 'object'),
  ('space_03', 'space', 3, 'common', 'מאדים', 'OBJ', 'modern', 'נקרא "הכוכב האדום" בגלל האבק החלוד שמכסה אותו.', 20203, 'object'),
  ('space_04', 'space', 4, 'common', 'טלסקופ', 'OBJ', 'modern', 'גלילאו גליליי גילה בעזרתו ירחים של צדק.', 20204, 'object'),
  ('space_05', 'space', 5, 'uncommon', 'לוויין', 'OBJ', 'modern', 'הלוויין המלאכותי הראשון, ספוטניק, שוגר ב-1957.', 20205, 'object'),
  ('space_06', 'space', 6, 'uncommon', 'שבתאי', 'OBJ', 'modern', 'הטבעות שלו עשויות בעיקר מקרח וסלעים.', 20206, 'object'),
  ('space_07', 'space', 7, 'uncommon', 'טיל', 'OBJ', 'modern', 'צריך מהירות עצומה כדי להשתחרר מכוח המשיכה.', 20207, 'object'),
  ('space_08', 'space', 8, 'rare', 'אסטרונאוט', 'OBJ', 'modern', 'ניל ארמסטרונג היה האדם הראשון שהלך על הירח, ב-1969.', 20208, 'object'),
  ('space_09', 'space', 9, 'rare', 'צדק', 'OBJ', 'modern', 'כוכב הלכת הגדול ביותר במערכת השמש.', 20209, 'object'),
  ('space_10', 'space', 10, 'epic', 'גלקסיה', 'OBJ', 'modern', 'שביל החלב הוא הגלקסיה שלנו.', 20210, 'object'),
  ('space_11', 'space', 11, 'legendary', 'השמש', 'OBJ', 'modern', 'האור שלה מגיע אלינו בתוך כ-8 דקות.', 20211, 'object'),
  ('space_12', 'space', 12, 'iconic', 'חור שחור', 'OBJ', 'modern', 'כוח המשיכה שלו חזק כל כך שאפילו אור לא בורח ממנו.', 20212, 'object'),
  ('inventions_01', 'inventions', 1, 'common', 'הגלגל', 'OBJ', 'modern', 'אחת ההמצאות העתיקות והחשובות בהיסטוריה.', 20301, 'object'),
  ('inventions_02', 'inventions', 2, 'common', 'נורה', 'OBJ', 'modern', 'תומס אדיסון שיפר אותה והפך אותה לשימושית בכל בית.', 20302, 'object'),
  ('inventions_03', 'inventions', 3, 'common', 'מצפן', 'OBJ', 'modern', 'המחט מצביעה צפונה בזכות השדה המגנטי של כדור הארץ.', 20303, 'object'),
  ('inventions_04', 'inventions', 4, 'common', 'טלפון', 'OBJ', 'modern', 'אלכסנדר גרהם בל רשם עליו פטנט ב-1876.', 20304, 'object'),
  ('inventions_05', 'inventions', 5, 'uncommon', 'מיקרוסקופ', 'OBJ', 'modern', 'חושף עולם שלם של יצורים זעירים.', 20305, 'object'),
  ('inventions_06', 'inventions', 6, 'uncommon', 'מצלמה', 'OBJ', 'modern', 'בצילומים הראשונים היה צריך לשבת בלי לזוז דקות ארוכות.', 20306, 'object'),
  ('inventions_07', 'inventions', 7, 'uncommon', 'רדיו', 'OBJ', 'modern', 'מעביר קול למרחקים בעזרת גלים.', 20307, 'object'),
  ('inventions_08', 'inventions', 8, 'rare', 'מטוס', 'OBJ', 'modern', 'האחים רייט טסו לראשונה ב-1903.', 20308, 'object'),
  ('inventions_09', 'inventions', 9, 'rare', 'קטר קיטור', 'OBJ', 'modern', 'הניע את המהפכה התעשייתית על מסילות הברזל.', 20309, 'object'),
  ('inventions_10', 'inventions', 10, 'epic', 'מחשב', 'OBJ', 'modern', 'המחשבים הראשונים היו בגודל של חדר שלם.', 20310, 'object'),
  ('inventions_11', 'inventions', 11, 'legendary', 'מכונת דפוס', 'OBJ', 'modern', 'יוהנס גוטנברג הפך את הדפוס לנפוץ באירופה במאה ה-15.', 20311, 'object'),
  ('inventions_12', 'inventions', 12, 'iconic', 'רובוט', 'OBJ', 'modern', 'המילה "רובוט" הגיעה ממחזה צ''כי משנת 1920.', 20312, 'object'),
  ('dinos_01', 'dinos', 1, 'common', 'דיפלודוקוס', 'OBJ', 'modern', 'צוואר ארוך וזנב ארוך עוד יותר.', 20401, 'object'),
  ('dinos_02', 'dinos', 2, 'common', 'סטגוזאורוס', 'OBJ', 'modern', 'לוחות גדולים לאורך הגב וקוצים בזנב.', 20402, 'object'),
  ('dinos_03', 'dinos', 3, 'common', 'אנקילוזאורוס', 'OBJ', 'modern', 'שריון על הגוף ואלה כבדה בקצה הזנב.', 20403, 'object'),
  ('dinos_04', 'dinos', 4, 'common', 'פרזאורולופוס', 'OBJ', 'modern', 'ציצה ארוכה ומעוקלת על הראש.', 20404, 'object'),
  ('dinos_05', 'dinos', 5, 'uncommon', 'טריצרטופס', 'OBJ', 'modern', 'שלוש קרניים ומגן גדול סביב הצוואר.', 20405, 'object'),
  ('dinos_06', 'dinos', 6, 'uncommon', 'פטרנודון', 'OBJ', 'modern', 'זוחל מעופף, ולא בדיוק דינוזאור.', 20406, 'object'),
  ('dinos_07', 'dinos', 7, 'uncommon', 'ולוצירפטור', 'OBJ', 'modern', 'היה בערך בגודל של תרנגול הודו.', 20407, 'object'),
  ('dinos_08', 'dinos', 8, 'rare', 'ממותה', 'OBJ', 'modern', 'קרובה של הפיל, עם פרווה עבה לעידן הקרח.', 20408, 'object'),
  ('dinos_09', 'dinos', 9, 'rare', 'נמר שן חרב', 'OBJ', 'modern', 'ניבים ארוכים כמו סכינים.', 20409, 'object'),
  ('dinos_10', 'dinos', 10, 'epic', 'ספינוזאורוס', 'OBJ', 'modern', 'מפרש גדול על הגב, וכנראה אהב לצוד דגים.', 20410, 'object'),
  ('dinos_11', 'dinos', 11, 'legendary', 'ברכיוזאורוס', 'OBJ', 'modern', 'הרגליים הקדמיות שלו ארוכות מהאחוריות.', 20411, 'object'),
  ('dinos_12', 'dinos', 12, 'iconic', 'טירנוזאורוס רקס', 'OBJ', 'modern', 'שיניים בגודל של בננה.', 20412, 'object'),
  ('food_01', 'food', 1, 'common', 'פלאפל', 'OBJ', 'modern', 'כדורים מטוגנים מחומוס או מפול.', 20501, 'object'),
  ('food_02', 'food', 2, 'common', 'חומוס', 'OBJ', 'modern', 'ממרח של גרגרי חומוס וטחינה.', 20502, 'object'),
  ('food_03', 'food', 3, 'common', 'פיצה', 'OBJ', 'modern', 'לפי הסיפור, פיצה מרגריטה נקראה על שם מלכת איטליה.', 20503, 'object'),
  ('food_04', 'food', 4, 'common', 'גלידה', 'OBJ', 'modern', 'בגביע או בכוס, פינוק של כל הקיץ.', 20504, 'object'),
  ('food_05', 'food', 5, 'uncommon', 'סושי', 'OBJ', 'modern', 'מנה יפנית של אורז מתובל בחומץ.', 20505, 'object'),
  ('food_06', 'food', 6, 'uncommon', 'המבורגר', 'OBJ', 'modern', 'קציצה בלחמנייה, מהמנות הפופולריות בעולם.', 20506, 'object'),
  ('food_07', 'food', 7, 'uncommon', 'שקשוקה', 'OBJ', 'modern', 'ביצים מבושלות ברוטב עגבניות ופלפלים.', 20507, 'object'),
  ('food_08', 'food', 8, 'rare', 'טאקו', 'OBJ', 'modern', 'טורטייה מקופלת מהמטבח המקסיקני.', 20508, 'object'),
  ('food_09', 'food', 9, 'rare', 'קרואסון', 'OBJ', 'modern', 'מאפה חמאה בצורת סהר, סמל של המאפייה הצרפתית.', 20509, 'object'),
  ('food_10', 'food', 10, 'epic', 'ראמן', 'OBJ', 'modern', 'מרק אטריות יפני עם אינספור סגנונות.', 20510, 'object'),
  ('food_11', 'food', 11, 'legendary', 'פאייה', 'OBJ', 'modern', 'תבשיל אורז מוולנסיה שבספרד.', 20511, 'object'),
  ('food_12', 'food', 12, 'iconic', 'סופגנייה', 'OBJ', 'modern', 'המאכל הכי מזוהה עם חנוכה.', 20512, 'object')
on conflict (id) do update set name_he = excluded.name_he, rarity = excluded.rarity, bio_he = excluded.bio_he, album = excluded.album, number = excluded.number;
